services:
  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: pokemon
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  api:
    build: 
      context: ./API_POKEMON
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

  react:
    container_name: react
    build:
      context: ./react-pokemons-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "8080:80"
    depends_on:
      - db


volumes:
  db-data:
    driver: local